# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
bioc_required: true
cache: packages


r:
  - release
  - devel



bioc_packages:
  - BiocCheck
  
r_packages:
  - devtools
r_github_packages:
  - jimhester/covr
  

     
after_success:
  - Rscript -e 'covr::codecov()'
